version: '3.1'

services:

    # text-oriented database
    elasticsearch:
      image: elasticsearch:8.10.2
      ports:
        - 9200:9200      
      environment:
        discovery.type: single-node
      volumes:
        - ./es-data:/usr/share/elasticsearch/data
      networks:
        - gestbd_net

networks:
    gestbd_net:
      external: true

