version: '3.1'

services:
    
    elasticsearch:
      image: elasticsearch:8.7.0
      ports:
        - 9200:9200      
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
        - xpack.security.enabled=false
      #volumes:
      #  - ./es-data:/usr/share/elasticsearch/data
      networks:
        - gestbd_net

networks:
    gestbd_net:
      external: true

